name = "edgerender"
type = "webpack"
account_id = "d6252a570c309c113744c9e11317e271"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

kv_namespaces = [
   { binding = "CACHE", id = "6756f784da8749bf9d2bb0440dd88852" }
]
